const $=s=>document.querySelector(s); let selected=null, sessionID=null, chatConfigured=false;
async function api(url,opts={}){const r=await fetch(url,{headers:{'content-type':'application/json'},...opts});const b=await r.json();if(!r.ok)throw Error(b.error||'request failed');return b}
function status(el,msg){$(el).textContent=msg}
function renderRepos(repos){const root=$('#repos');root.innerHTML='';if(!repos.length){root.textContent='No snapshots yet.';return}repos.forEach(r=>{const b=document.createElement('button');const name=r.canonical_url.replace('https://github.com/','').replace('.git','');const sha=r.resolved_commit_sha?` · ${r.resolved_commit_sha.slice(0,10)}`:'';b.className='repo '+(selected?.id===r.id?'selected':'');b.innerHTML=`<strong>${name}</strong><small>${r.status}${sha}</small>`;b.onclick=()=>{selected=r;sessionID=null;$('#question').disabled=r.status!=='ready';$('#ask').disabled=r.status!=='ready';status('#question-status',r.status==='ready'?'Ready for cited retrieval.':'Index status: '+r.status);renderRepos(repos)};root.append(b)})}
async function refresh(){try{renderRepos(await api('/api/repos'))}catch(e){status('#provider',e.message)}}
async function poll(job){if(!job?.id)return;const tick=async()=>{try{const j=await api('/api/jobs/'+job.id);status('#provider',`${j.phase}: ${j.files_indexed} files · ${j.chunks} chunks`);await refresh();if(j.cancellable||['queued','cloning','resolving','indexing'].includes(j.phase))setTimeout(tick,1200)}catch(e){status('#provider',e.message)}};tick()}
$('#index').onclick=async()=>{try{const body={url:$('#repo-url').value,ref:$('#repo-ref').value};const out=await api('/api/repos',{method:'POST',body:JSON.stringify(body)});status('#provider',out.reused?'Existing snapshot selected.':'Index job queued.');selected=out.repository;await refresh();poll(out.job)}catch(e){status('#provider',e.message)}};
$('#refresh').onclick=refresh;
function showContext(pack){return pack.evidence.map(e=>`<article id="${e.id}"><code>[${e.id}] ${e.path}:${e.start_line}-${e.end_line}</code><pre>${escapeHTML(e.snippet)}</pre><small>${e.symbol||'module'} · ${e.excerpt_sha256.slice(0,12)}… · ${e.retrieval_sources.join(', ')}</small></article>`).join('')||'<p>No evidence returned.</p>'}
function linkCitations(text){return escapeHTML(text).replace(/\[(e\d+)\]/g,'<a href="#$1">[$1]</a>')}
$('#ask').onclick=async()=>{if(!selected)return;const button=$('#ask');button.disabled=true;status('#question-status',chatConfigured?'Generating a cited answer from the bounded context pack…':'Retrieving a cited context pack…');try{const endpoint=chatConfigured?'/api/answer':'/api/context';const out=await api(endpoint,{method:'POST',body:JSON.stringify({repository_id:selected.id,question:$('#question').value,session_id:sessionID})});const pack=chatConfigured?out.answer.context:out.context;sessionID=out.session.id;$('#note').disabled=false;$('#remember').disabled=false;$('#session').textContent=`Session ${sessionID.slice(0,12)}… scoped to ${pack.repository.commit_sha.slice(0,12)}. ${pack.retrieval.degraded?'Lexical retrieval only; hosted embedding query credentials are unavailable.':'Hybrid retrieval active.'}`;const generated=chatConfigured?`<article class="generated"><strong>ANSWER</strong><p>${linkCitations(out.answer.text)}</p></article>`:'';$('#answer').innerHTML=generated+showContext(pack);status('#question-status',chatConfigured?'Answer validated against linked source evidence.':'Context pack is source-cited. Configure hosted chat to generate an answer.')}catch(e){status('#question-status',e.message)}finally{button.disabled=false}};
$('#remember').onclick=async()=>{try{await api('/api/sessions/'+sessionID+'/remember',{method:'POST',body:JSON.stringify({note:$('#note').value})});$('#note').value='';status('#question-status','Note retained in this snapshot-scoped session.')}catch(e){status('#question-status',e.message)}};
function escapeHTML(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}
(async()=>{try{const h=await api('/api/health');chatConfigured=h.chat_configured;status('#provider',h.embedding_configured?`Hosted embeddings configured (${h.embedding_provider}).`: 'Hosted embedding credentials required before indexing. No local model is used.')}catch(e){status('#provider',e.message)}refresh()})();
